---
title: "Movie Modeling"
output: html_document
---
## Overview
As proposed in initial project submission, this project intends to perform study on the movie industry trends and model  
prediction for the future trends.

### Number of Movies/Year

```{r echo=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
DIR<-paste(Sys.getenv("HOME"), "/datascience/springboard/project/", sep="")
setwd(DIR)
df<- read.table(paste(DIR, "MergeDataSet.csv", sep=""), sep=",", header=TRUE)
ldf <- tbl_df(df)
```

```{r echo=FALSE, message=FALSE}
yrsum<-ldf %>% group_by(Year) %>% summarise(n())
p<-ggplot(yrsum, aes(x=Year, y=`n()`)) + geom_bar(stat="identity", width = 1, fill="steelblue") + theme_minimal()
print(p)
```
### Model Linear Regression 

```{r}
#train_data <- subset(ldf, Year > 1975)
train_data <- ldf
yrsum<-train_data %>% group_by(Year) %>% summarise(n())
mean.num_of_movie=mean(yrsum$`n()`, na.rm=T)
model1 <- lm(yrsum$`n()`~Year, data=yrsum)
p<-ggplot(yrsum, aes(x=Year, y=`n()`)) + geom_point() +  
  geom_hline(yintercept=mean.num_of_movie) + 
  geom_abline(intercept=model1$coefficients[1], slope=model1$coefficients[2], color="red")

print(p)
```

